[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1.22.0", features = ["serde-str"] }
serde = { version = "1.0.136", features = ["derive"] }
csv = "1.1.6"