[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.7.6"
csv = "1.1.6"
rust_decimal = { version = "1.25.0", features = ["serde-str"] }
serde = { version = "1.0.140", features = ["derive"] }